### ISSUE TITLE
Problem with inference with dynamic batches

### ISSUE THREAD

**Issue by Kr4is** [zerollzeng/tiny-tensorrt#28]
Hi @zerollzeng !

First of all, thank you for this project, it is very interesting and useful!

I am trying to do inference with batches, for this I have exported a model in Pytorch to ONNX with dynamic input and output batch size.

Later I have modified the file "unit_test.cpp" to carry out the tests, the final code is as follows:

```
void test_onnx(const std::string& onnxModelpath, const std::string& imagePath1, const std::string& imagePath2) {
    std::string engineFile = "";
    const std::vector<std::string> customOutput;
    std::vector<std::vector<float>> calibratorData;
    int maxBatchSize = 2;
    int mode = 0;
    Trt* onnx_net = new Trt();
    onnx_net->CreateEngine(onnxModelpath, engineFile, customOutput, maxBatchSize, mode, calibratorData);

    cv::Mat image1, image2;
    image1 = cv::imread(imagePath1, 1);
    image2 = cv::imread(imagePath2, 1);
    if ( !image1.data || !image2.data )
    {
        printf("No image data \n");
        return;
    }
    cv::Mat resized_image1, resized_image2;
    cv::resize(image1, resized_image1, cv::Size(32,32));
    cv::resize(image2, resized_image2, cv::Size(32,32));
    std::vector<cv::Mat> imgs = {resized_image1, resized_image2};
    
    int N = 2;
    int C = 3;
    int H = 32;
    int W = 32;
    std::vector<float> inputData;
    inputData.resize(N * C * H * W);
    
    for(int n=0; n<N;n++) {
        for(int c=0;c<3;c++) {
            for(int i=0;i<H*W;i++) {
                inputData[i+c*H*W+n*3*W*H] = (float)imgs[n].data[i*3+c];
            }
        }
    }

    std::vector<float> result;

    onnx_net->DataTransfer(inputData, 0, true);

    onnx_net->Forward();

    onnx_net->DataTransfer(result, 1, false);

    for (auto a : result){
        std::cout << a << std::endl;
    }
}
```

The project compiles without problems, but when I run the program I get the following error:

```
./unit_test --onnx_path models/boe_simple_no_norm_opset_11_dyn_2_batch.onnx --image_path1 ./nw1.png --image_path2 ./ne1.png
[2020-08-18 11:45:25.543] [info] create plugin factory
[2020-08-18 11:45:25.543] [info] yolo3 params: class: 1, netSize: 416 
[2020-08-18 11:45:25.543] [info] upsample params: scale: 2
[2020-08-18 11:45:25.543] [info] build onnx engine from models/boe_simple_no_norm_opset_11_dyn_2_batch.onnx...
----------------------------------------------------------------
Input filename:   models/boe_simple_no_norm_opset_11_dyn_2_batch.onnx
ONNX IR version:  0.0.6
Opset version:    11
Producer name:    pytorch
Producer version: 1.6
Domain:           
Model version:    0
Doc string:       
----------------------------------------------------------------
/home/mads/bruno/Documentos/TensorRT/parsers/onnx/onnx2trt_utils.cpp:216: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
/home/mads/bruno/Documentos/TensorRT/parsers/onnx/onnx2trt_utils.cpp:216: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
/home/mads/bruno/Documentos/TensorRT/parsers/onnx/onnx2trt_utils.cpp:216: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
/home/mads/bruno/Documentos/TensorRT/parsers/onnx/onnx2trt_utils.cpp:216: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
Calling isShapeTensor before the entire network is constructed may result in an inaccurate result.
Calling isShapeTensor before the entire network is constructed may result in an inaccurate result.
Calling isShapeTensor before the entire network is constructed may result in an inaccurate result.
input  -------> 11 
11  -------> 12 
12  -------> 13 
13  -------> 14 
14  -------> (Unnamed Layer* 4) [Shape]_output 
 -------> (Unnamed Layer* 5) [Constant]_output 
(Unnamed Layer* 4) [Shape]_output (Unnamed Layer* 5) [Constant]_output  -------> (Unnamed Layer* 6) [Gather]_output 
 -------> (Unnamed Layer* 7) [Constant]_output 
(Unnamed Layer* 4) [Shape]_output (Unnamed Layer* 7) [Constant]_output  -------> (Unnamed Layer* 8) [Gather]_output 
 -------> (Unnamed Layer* 9) [Constant]_output 
(Unnamed Layer* 4) [Shape]_output (Unnamed Layer* 9) [Constant]_output  -------> (Unnamed Layer* 10) [Gather]_output 
(Unnamed Layer* 8) [Gather]_output (Unnamed Layer* 10) [Gather]_output  -------> (Unnamed Layer* 11) [ElementWise]_output 
 -------> (Unnamed Layer* 12) [Constant]_output 
(Unnamed Layer* 4) [Shape]_output (Unnamed Layer* 12) [Constant]_output  -------> (Unnamed Layer* 13) [Gather]_output 
(Unnamed Layer* 11) [ElementWise]_output (Unnamed Layer* 13) [Gather]_output  -------> (Unnamed Layer* 14) [ElementWise]_output 
(Unnamed Layer* 6) [Gather]_output (Unnamed Layer* 14) [ElementWise]_output  -------> (Unnamed Layer* 15) [Concatenation]_output 
14 (Unnamed Layer* 15) [Concatenation]_output  -------> 15 
 -------> (Unnamed Layer* 17) [Constant]_output 
 -------> (Unnamed Layer* 18) [Constant]_output 
15 (Unnamed Layer* 18) [Constant]_output  -------> (Unnamed Layer* 19) [Matrix Multiply]_output 
 -------> (Unnamed Layer* 20) [Constant]_output 
(Unnamed Layer* 20) [Constant]_output  -------> (Unnamed Layer* 21) [Shuffle]_output 
(Unnamed Layer* 19) [Matrix Multiply]_output (Unnamed Layer* 21) [Shuffle]_output  -------> 16 
16  -------> 17 
 -------> (Unnamed Layer* 24) [Constant]_output 
 -------> (Unnamed Layer* 25) [Constant]_output 
17 (Unnamed Layer* 25) [Constant]_output  -------> (Unnamed Layer* 26) [Matrix Multiply]_output 
 -------> (Unnamed Layer* 27) [Constant]_output 
(Unnamed Layer* 27) [Constant]_output  -------> (Unnamed Layer* 28) [Shuffle]_output 
(Unnamed Layer* 26) [Matrix Multiply]_output (Unnamed Layer* 28) [Shuffle]_output  -------> 18 
18  -------> 19 
 -------> (Unnamed Layer* 31) [Constant]_output 
 -------> (Unnamed Layer* 32) [Constant]_output 
19 (Unnamed Layer* 32) [Constant]_output  -------> (Unnamed Layer* 33) [Matrix Multiply]_output 
 -------> (Unnamed Layer* 34) [Constant]_output 
(Unnamed Layer* 34) [Constant]_output  -------> (Unnamed Layer* 35) [Shuffle]_output 
(Unnamed Layer* 33) [Matrix Multiply]_output (Unnamed Layer* 35) [Shuffle]_output  -------> output 
[2020-08-18 11:45:25.799] [info] fp16 support: false
[2020-08-18 11:45:25.799] [info] int8 support: true
[2020-08-18 11:45:25.799] [info] Max batchsize: 2
[2020-08-18 11:45:25.799] [info] Max workspace size: 10485760
[2020-08-18 11:45:25.799] [info] Number of DLA core: 0
[2020-08-18 11:45:25.799] [info] Max DLA batchsize: 268435456
[2020-08-18 11:45:25.799] [info] Current use DLA core: 0
[2020-08-18 11:45:25.799] [info] build engine...
Network has dynamic or shape inputs, but no optimization profile has been defined.
Network validation failed.
unit_test: /home/mads/bruno/Documentos/tiny-tensorrt/Trt.cpp:318: void Trt::BuildEngine(nvinfer1::IBuilder*, nvinfer1::INetworkDefinition*, const std::vector<std::vector<float> >&, int, int): Assertion `mEngine != nullptr' failed.
```

I have tried to define the optimization profiles that the error comments by adding the following code in line 258 of the Trt.cpp file:

```
// Create an optimization profile so that we can specify a range of input dimensions.
auto profile = builder->createOptimizationProfile();
// This profile will be valid for all images whose size falls in the range of [(1, 3, 32, 32), (16, 3, 32, 32)]
// but TensorRT will optimize for (2, 3, 32, 32)
// We do not need to check the return of setDimension and addOptimizationProfile here as all dims are explicitly set
profile->setDimensions(network->getInput(0)->getName(), OptProfileSelector::kMIN, Dims4{1, 3, 32, 32});
profile->setDimensions(network->getInput(0)->getName(), OptProfileSelector::kOPT, Dims4{2, 3, 32, 32});
profile->setDimensions(network->getInput(0)->getName(), OptProfileSelector::kMAX, Dims4{16, 3, 32, 32});
config->addOptimizationProfile(profile);
```

The project compiled successfully again, but when executing I get a new error:

```
./unit_test --onnx_path models/boe_simple_no_norm_opset_11_dyn_2_batch.onnx --image_path1 ./nw1.png --image_path2 ./ne1.png
[2020-08-18 11:55:09.631] [info] create plugin factory
[2020-08-18 11:55:09.632] [info] yolo3 params: class: 1, netSize: 416 
[2020-08-18 11:55:09.632] [info] upsample params: scale: 2
[2020-08-18 11:55:09.632] [info] build onnx engine from models/boe_simple_no_norm_opset_11_dyn_2_batch.onnx...
----------------------------------------------------------------
Input filename:   models/boe_simple_no_norm_opset_11_dyn_2_batch.onnx
ONNX IR version:  0.0.6
Opset version:    11
Producer name:    pytorch
Producer version: 1.6
Domain:           
Model version:    0
Doc string:       
----------------------------------------------------------------
/home/mads/bruno/Documentos/TensorRT/parsers/onnx/onnx2trt_utils.cpp:216: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
/home/mads/bruno/Documentos/TensorRT/parsers/onnx/onnx2trt_utils.cpp:216: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
/home/mads/bruno/Documentos/TensorRT/parsers/onnx/onnx2trt_utils.cpp:216: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
/home/mads/bruno/Documentos/TensorRT/parsers/onnx/onnx2trt_utils.cpp:216: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
Calling isShapeTensor before the entire network is constructed may result in an inaccurate result.
Calling isShapeTensor before the entire network is constructed may result in an inaccurate result.
Calling isShapeTensor before the entire network is constructed may result in an inaccurate result.
input  -------> 11 
11  -------> 12 
12  -------> 13 
13  -------> 14 
14  -------> (Unnamed Layer* 4) [Shape]_output 
 -------> (Unnamed Layer* 5) [Constant]_output 
(Unnamed Layer* 4) [Shape]_output (Unnamed Layer* 5) [Constant]_output  -------> (Unnamed Layer* 6) [Gather]_output 
 -------> (Unnamed Layer* 7) [Constant]_output 
(Unnamed Layer* 4) [Shape]_output (Unnamed Layer* 7) [Constant]_output  -------> (Unnamed Layer* 8) [Gather]_output 
 -------> (Unnamed Layer* 9) [Constant]_output 
(Unnamed Layer* 4) [Shape]_output (Unnamed Layer* 9) [Constant]_output  -------> (Unnamed Layer* 10) [Gather]_output 
(Unnamed Layer* 8) [Gather]_output (Unnamed Layer* 10) [Gather]_output  -------> (Unnamed Layer* 11) [ElementWise]_output 
 -------> (Unnamed Layer* 12) [Constant]_output 
(Unnamed Layer* 4) [Shape]_output (Unnamed Layer* 12) [Constant]_output  -------> (Unnamed Layer* 13) [Gather]_output 
(Unnamed Layer* 11) [ElementWise]_output (Unnamed Layer* 13) [Gather]_output  -------> (Unnamed Layer* 14) [ElementWise]_output 
(Unnamed Layer* 6) [Gather]_output (Unnamed Layer* 14) [ElementWise]_output  -------> (Unnamed Layer* 15) [Concatenation]_output 
14 (Unnamed Layer* 15) [Concatenation]_output  -------> 15 
 -------> (Unnamed Layer* 17) [Constant]_output 
 -------> (Unnamed Layer* 18) [Constant]_output 
15 (Unnamed Layer* 18) [Constant]_output  -------> (Unnamed Layer* 19) [Matrix Multiply]_output 
 -------> (Unnamed Layer* 20) [Constant]_output 
(Unnamed Layer* 20) [Constant]_output  -------> (Unnamed Layer* 21) [Shuffle]_output 
(Unnamed Layer* 19) [Matrix Multiply]_output (Unnamed Layer* 21) [Shuffle]_output  -------> 16 
16  -------> 17 
 -------> (Unnamed Layer* 24) [Constant]_output 
 -------> (Unnamed Layer* 25) [Constant]_output 
17 (Unnamed Layer* 25) [Constant]_output  -------> (Unnamed Layer* 26) [Matrix Multiply]_output 
 -------> (Unnamed Layer* 27) [Constant]_output 
(Unnamed Layer* 27) [Constant]_output  -------> (Unnamed Layer* 28) [Shuffle]_output 
(Unnamed Layer* 26) [Matrix Multiply]_output (Unnamed Layer* 28) [Shuffle]_output  -------> 18 
18  -------> 19 
 -------> (Unnamed Layer* 31) [Constant]_output 
 -------> (Unnamed Layer* 32) [Constant]_output 
19 (Unnamed Layer* 32) [Constant]_output  -------> (Unnamed Layer* 33) [Matrix Multiply]_output 
 -------> (Unnamed Layer* 34) [Constant]_output 
(Unnamed Layer* 34) [Constant]_output  -------> (Unnamed Layer* 35) [Shuffle]_output 
(Unnamed Layer* 33) [Matrix Multiply]_output (Unnamed Layer* 35) [Shuffle]_output  -------> output 
[2020-08-18 11:55:09.887] [info] fp16 support: false
[2020-08-18 11:55:09.887] [info] int8 support: true
[2020-08-18 11:55:09.887] [info] Max batchsize: 2
[2020-08-18 11:55:09.887] [info] Max workspace size: 10485760
[2020-08-18 11:55:09.887] [info] Number of DLA core: 0
[2020-08-18 11:55:09.887] [info] Max DLA batchsize: 268435456
[2020-08-18 11:55:09.887] [info] Current use DLA core: 0
[2020-08-18 11:55:09.887] [info] build engine...
Some tactics do not have sufficient workspace memory to run. Increasing workspace size may increase performance, please check verbose output.
Detected 1 inputs and 1 output network tensors.
[2020-08-18 11:55:10.630] [info] serialize engine to 
[2020-08-18 11:55:10.630] [warning] empty engine file name, skip save
[2020-08-18 11:55:10.630] [info] create execute context and malloc device memory...
[2020-08-18 11:55:10.630] [info] init engine...
[2020-08-18 11:55:10.631] [info] malloc device memory
nbBingdings: 2
[2020-08-18 11:55:10.632] [info] input: 
[2020-08-18 11:55:10.632] [info] binding bindIndex: 0, name: input, size in byte: -24576
[2020-08-18 11:55:10.632] [info] binding dims with 4 dimemsion
-1 x 3 x 32 x 32   
CUDA error 2 at /home/mads/bruno/Documentos/tiny-tensorrt/utils.h:51
```

This error is due to the fact that a negative number of memory is being reserved, since when a dimension is dynamic it has a value of -1, so the following line (from InitEngine() function) does not seem to work correctly:
```
int64_t totalSize = volume(dims) * mBatchSize * getElementSize(dtype);
```

I have tried changing the line to the following to accommodate the correct memory space:
```
int64_t totalSize = -1 * volume(dims) * 2 * getElementSize(dtype);
```

When executing the program again, the end of the execution is reached but showing the following output, so it is not performing the inference correctly:
```
...
[2020-08-18 12:05:29.763] [info] fp16 support: false
[2020-08-18 12:05:29.763] [info] int8 support: true
[2020-08-18 12:05:29.763] [info] Max batchsize: 2
[2020-08-18 12:05:29.763] [info] Max workspace size: 10485760
[2020-08-18 12:05:29.763] [info] Number of DLA core: 0
[2020-08-18 12:05:29.763] [info] Max DLA batchsize: 268435456
[2020-08-18 12:05:29.763] [info] Current use DLA core: 0
[2020-08-18 12:05:29.763] [info] build engine...
Some tactics do not have sufficient workspace memory to run. Increasing workspace size may increase performance, please check verbose output.
Detected 1 inputs and 1 output network tensors.
[2020-08-18 12:05:30.484] [info] serialize engine to 
[2020-08-18 12:05:30.484] [warning] empty engine file name, skip save
[2020-08-18 12:05:30.484] [info] create execute context and malloc device memory...
[2020-08-18 12:05:30.484] [info] init engine...
[2020-08-18 12:05:30.485] [info] malloc device memory
nbBingdings: 2
-3072 2
[2020-08-18 12:05:30.485] [info] input: 
[2020-08-18 12:05:30.485] [info] binding bindIndex: 0, name: input, size in byte: 24576
[2020-08-18 12:05:30.485] [info] binding dims with 4 dimemsion
-1 x 3 x 32 x 32   
-8 2
[2020-08-18 12:05:30.486] [info] output: 
[2020-08-18 12:05:30.486] [info] binding bindIndex: 1, name: (Unnamed Layer* 37) [Softmax]_output, size in byte: 64
[2020-08-18 12:05:30.486] [info] binding dims with 2 dimemsion
-1 x 8   
Explicit batch network detected and batch size specified, use execute without batch size instead.
Parameter check failed at: engine.cpp::resolveSlots::1092, condition: allInputDimensionsSpecified(routine)
[2020-08-18 12:05:30.487] [info] net forward takes 0.019456 ms
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
```

If I export the model with an explicit number of batches, the inference succeeds, but this results in having to export a model for each batch size, which is not optimal.

Do you know how I could do batch inference directly from TinyTensorRT?

Thanks in advance!

**System environment:**
 - OS: Ubuntu 18.04
 - TensorRT version: 7.0
 - Graphic card: Nvidia 1050 Ti

**Comment by zerollzeng** [comment]
@Kr4is  Hi thanks for your feedback. you want a dynamic batch support, right? what is your scenario? can you describe it briefly? I am plan to to upgrade tiny-tensorrt when TensorRT 8 version release, so I might consider add this support.
and for your problem, perhaps you can take a look at this
https://github.com/NVIDIA/TensorRT/issues/370#issuecomment-583124689

I'm not very familiar with your problem, but I would like to dig into it with you :smile:

**Comment by Kr4is** [comment]
@zerollzeng hi! Exactly, i want a dynamic batch support. 

My scenario is the following: 
I have images of size 32x32 with 3 channels, then the input data is 3x32x32.
From Pytorch i can export the network to ONNX format with different number of batches, then, if i export with 1 batch i have an input of 1x3x32x32, if i export the model with 16 batches i have an input of 16x3x32x32... But if i export the model with dynamic batches the model have a input like -1x3x32x32.

For this case, dynamic batch size, i can say in tensor rt the optimization profile to set the minimum, maximum and optimization sizes with the network should works. in order to do the inference depending the input size, in runtime.

I see in the code the variable batchsize, and i think that tinytensorrt support dynamic batch support, but its already not supported? 

I try to test the onnx dynamic model with [https://github.com/NVIDIA/TensorRT/tree/master/samples/opensource/trtexec](trtexec) and it works correctly.

To make the modifications that i said on the issue comment i follow [https://developer.nvidia.com/blog/speeding-up-deep-learning-inference-using-tensorrt/](this post). But it seems need more thing than my changes.

Do you have any idea to get this feature?

Thank you for the quick response!

**Comment by zerollzeng** [comment]
yeah tiny-tensorrt does not support dynamic batch now,I will take a look
tomorrow

Bruno Cabado <notifications@github.com> 于 2020年8月18日周二 下午7:33写道：

**Comment by zerollzeng** [comment]
> This error is due to the fact that a negative number of memory is being reserved, since when a dimension is dynamic it has a value of -1, so the following line (from InitEngine() function) does not seem to work correctly:
> 
> ```
> int64_t totalSize = volume(dims) * mBatchSize * getElementSize(dtype);
> ```
> 
> I have tried changing the line to the following to accommodate the correct memory space:
> 
> ```
> int64_t totalSize = -1 * volume(dims) * 2 * getElementSize(dtype);
> ```
> 
> When executing the program again, the end of the execution is reached but showing the following output, so it is not performing the inference correctly:

@Kr4is hi I read your problem again and browse the nvidia blog you mention above, maybe you should set the max batchsize to 32 instead of 2? and malloc device memory with   -1 * volume(dims) * 32 * getElementSize(dtype)

**Comment by zerollzeng** [comment]
and if not working perhaps explicitBatch is the reason, take a look at https://docs.nvidia.com/deeplearning/tensorrt/developer-guide/index.html#import_onnx_c, as it mention:
Note: In TensorRT 7.0, the ONNX parser only supports full-dimensions mode, meaning that your network definition must be created with the explicitBatch flag set. For more information, see Working With Dynamic Shapes.

**Comment by Kr4is** [comment]
@zerollzeng Hi!
I did the changes that you say but still not working.
I have found the example code that is used in the post that I mentioned earlier and it seems that there it does batches with different number of images. The code is [here](https://github.com/NVIDIA-developer-blog/code-samples/blob/master/posts/TensorRT-introduction/simpleOnnx_1.cpp).

The structure used is very similar to that of TinyTensorRT, with the changes that I mentioned in the first comment.

On the other hand I know the example you mention of "Working with Dynamic Shapes", it can be found [here](https://github.com/NVIDIA/TensorRT/blob/master/samples/opensource/sampleDynamicReshape/sampleDynamicReshape.cpp). But I think it is very complex for this case as it more closely resembles the simpleOnnx_1 example.

Note that in the DynamicReshape example it works with different size of images but in the simpleOnnx example it works with different number of images but all of the same size.

I think that simpleOnnx is better way to have a batched inference in this case.

But i don't know what changes need to be added to make it work in this case. Any idea?

**Comment by zerollzeng** [comment]
> I have found the example code that is used in the post that I mentioned earlier and it seems that there it does batches with different number of images. The code is [here](https://github.com/NVIDIA-developer-blog/code-samples/blob/master/posts/TensorRT-introduction/simpleOnnx_1.cpp).

I read the code, I don't think it's a dynamic batch. perhaps
```c++
    auto profile = builder->createOptimizationProfile();
    profile->setDimensions(network->getInput(0)->getName(), OptProfileSelector::kMIN, Dims4{1, 3, 256 , 256});
    profile->setDimensions(network->getInput(0)->getName(), OptProfileSelector::kOPT, Dims4{1, 3, 256 , 256});
    profile->setDimensions(network->getInput(0)->getName(), OptProfileSelector::kMAX, Dims4{32, 3, 256 , 256});    
    config->addOptimizationProfile(profile);
```
cause some confusion, if you read this fuction
```c++
void launchInference(IExecutionContext* context, cudaStream_t stream, vector<float> const& inputTensor, vector<float>& outputTensor, void** bindings, int batchSize)
{
    int inputId = getBindingInputIndex(context);
    cudaMemcpyAsync(bindings[inputId], inputTensor.data(), inputTensor.size() * sizeof(float), cudaMemcpyHostToDevice, stream);
    context->enqueueV2(bindings, stream, nullptr);
    cudaMemcpyAsync(outputTensor.data(), bindings[1 - inputId], outputTensor.size() * sizeof(float), cudaMemcpyDeviceToHost, stream);

}
```
you will find that batchSize is not being used at all, for this sample, eg I want a max batch size of 16 engine, I just create it with batchSize=16, when excution I just put the 1,2,3...16 images to execution context and retrieve the corresponding number of output, maybe you can do it this way too.

**Comment by zerollzeng** [comment]
BTW you can make it work with trtexec, does it give some efficiency improvement? for example latency.

**Comment by Kr4is** [comment]
I think with this code: 
```
    auto profile = builder->createOptimizationProfile();
    profile->setDimensions(network->getInput(0)->getName(), OptProfileSelector::kMIN, Dims4{1, 3, 256 , 256});
    profile->setDimensions(network->getInput(0)->getName(), OptProfileSelector::kOPT, Dims4{1, 3, 256 , 256});
    profile->setDimensions(network->getInput(0)->getName(), OptProfileSelector::kMAX, Dims4{32, 3, 256 , 256});    
    config->addOptimizationProfile(profile);
```
Makes the engine capable of receiving different amount of images as input tensor. from 1 to 32 and optimizing for inputs of 1 specific image.

And then the launchInference() function depends only on the size of the input.

I test the application with trtexec, i make my dynamic model with this configuration:
`--minShapes=input:1x3x32x32 --optShapes=input:8x3x32x32 --maxShapes=input:16x3x32x32`

Meaning that the number of entries it supports is between 1 and 16, being optimized for when the entry is 8 images.

When i execute with size 1x3x32x32 i obtain this performance:
```
[08/19/2020-09:42:23] [I] Host latency
[08/19/2020-09:42:23] [I] min: 0.179932 ms (end to end 0.189148 ms)
[08/19/2020-09:42:23] [I] max: 1.3418 ms (end to end 1.49493 ms)
[08/19/2020-09:42:23] [I] mean: 0.189297 ms (end to end 0.347664 ms)
[08/19/2020-09:42:23] [I] median: 0.186646 ms (end to end 0.34314 ms)
[08/19/2020-09:42:23] [I] percentile: 0.218628 ms at 99% (end to end 0.469727 ms at 99%)
[08/19/2020-09:42:23] [I] throughput: 0 qps
[08/19/2020-09:42:23] [I] walltime: 3.00055 s
[08/19/2020-09:42:23] [I] GPU Compute
[08/19/2020-09:42:23] [I] min: 0.174072 ms
[08/19/2020-09:42:23] [I] max: 1.33325 ms
[08/19/2020-09:42:23] [I] mean: 0.183061 ms
[08/19/2020-09:42:23] [I] median: 0.180298 ms
[08/19/2020-09:42:23] [I] percentile: 0.211975 ms at 99%
[08/19/2020-09:42:23] [I] total compute time: 2.97328 s
```

When i execute with size 8x3x32x32 (optimized) i obtain this performance:
```
[08/19/2020-09:44:23] [I] Host latency
[08/19/2020-09:44:23] [I] min: 0.210205 ms (end to end 0.222412 ms)
[08/19/2020-09:44:23] [I] max: 0.423462 ms (end to end 0.622559 ms)
[08/19/2020-09:44:23] [I] mean: 0.21641 ms (end to end 0.388994 ms)
[08/19/2020-09:44:23] [I] median: 0.2146 ms (end to end 0.386963 ms)
[08/19/2020-09:44:23] [I] percentile: 0.239349 ms at 99% (end to end 0.43364 ms at 99%)
[08/19/2020-09:44:23] [I] throughput: 0 qps
[08/19/2020-09:44:23] [I] walltime: 3.00073 s
[08/19/2020-09:44:23] [I] GPU Compute
[08/19/2020-09:44:23] [I] min: 0.19751 ms
[08/19/2020-09:44:23] [I] max: 0.410629 ms
[08/19/2020-09:44:23] [I] mean: 0.203556 ms
[08/19/2020-09:44:23] [I] median: 0.201721 ms
[08/19/2020-09:44:23] [I] percentile: 0.226303 ms at 99%
[08/19/2020-09:44:23] [I] total compute time: 2.97558 s
```

And finally when i execute with size 16x3x32x32 i obtain:
```
[08/19/2020-09:45:32] [I] Host latency
[08/19/2020-09:45:32] [I] min: 0.237549 ms (end to end 0.25 ms)
[08/19/2020-09:45:32] [I] max: 0.53392 ms (end to end 0.748444 ms)
[08/19/2020-09:45:32] [I] mean: 0.244937 ms (end to end 0.431445 ms)
[08/19/2020-09:45:32] [I] median: 0.242432 ms (end to end 0.427429 ms)
[08/19/2020-09:45:32] [I] percentile: 0.272858 ms at 99% (end to end 0.553711 ms at 99%)
[08/19/2020-09:45:32] [I] throughput: 0 qps
[08/19/2020-09:45:32] [I] walltime: 3.00049 s
[08/19/2020-09:45:32] [I] GPU Compute
[08/19/2020-09:45:32] [I] min: 0.217102 ms
[08/19/2020-09:45:32] [I] max: 0.514038 ms
[08/19/2020-09:45:32] [I] mean: 0.224747 ms
[08/19/2020-09:45:32] [I] median: 0.222229 ms
[08/19/2020-09:45:32] [I] percentile: 0.251907 ms at 99%
[08/19/2020-09:45:32] [I] total compute time: 2.96756 s
```

**Comment by zerollzeng** [comment]
Looks like the batch size does not affect the forward latency, so you can just build engine with a large batchsize and inference with images less than the max batch size?
I am plan to upgrade tiny-tensorrt when TensorRT 8 release come out, maybe next month with newer 30 series card. will add dynamic shape support, maybe add empty tensor support too.

**Comment by Kr4is** [comment]
Yes, for now I will do it as you say. My model is very simple and there are not going to be big differences in performance. I'll then wait for that new release of TinyTensorRt for the inference with batches. 

If at any time I implement something that may be interesting for TinyTensorRt, I will let you know! 

Thank you very much for this project!

**Comment by zerollzeng** [comment]
Thanks for your feedback and contribution!

**Comment by zerollzeng** [comment]
@Kr4is Dynamic shape has been added to latest tiny-tensorrt, but not test broadly, if you have interest you could take a try

**Comment by zerollzeng** [comment]
I found some bugs during testing, will fix it as soon as possible.
